[Fix] python security bugs

diff --git a/scripts/docker/zeppelin/bin/Dockerfile-Base b/scripts/docker/zeppelin/bin/Dockerfile-Base
--- a/scripts/docker/zeppelin/bin/Dockerfile-Base
+++ b/scripts/docker/zeppelin/bin/Dockerfile-Base
@@ -33,36 +33,45 @@ RUN echo "$LOG_TAG install basic packages" && \
     apt-get -y update && \
     # Switch back to install JRE instead of JDK when moving to JDK9 or later.
     DEBIAN_FRONTEND=noninteractive apt-get install -y locales language-pack-en tini openjdk-8-jdk-headless wget unzip sudo && \
+    /usr/bin/wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba && \
     # Cleanup
     rm -rf /var/lib/apt/lists/* && \
     apt-get autoclean && \
     apt-get clean
 
-# Install conda to manage python and R packages
-ARG miniconda_version="py37_4.9.2"
-# Hashes via https://docs.conda.io/en/latest/miniconda_hashes.html
-ARG miniconda_sha256="79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31"
-# Install python and R packages via conda
+## Install conda to manage python and R packages
+#ARG miniconda_version="py37_4.9.2"
+## Hashes via https://docs.conda.io/en/latest/miniconda_hashes.html
+#ARG miniconda_sha256="79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31"
+## Install python and R packages via conda
+#COPY env_python_3_with_R.yml /env_python_3_with_R.yml
+#COPY Miniconda3-${miniconda_version}-Linux-x86_64.sh /miniconda.sh
+#RUN set -ex && \
+#    #wget -nv https://repo.anaconda.com/miniconda/Miniconda3-${miniconda_version}-Linux-x86_64.sh -O miniconda.sh && \
+#    echo "${miniconda_sha256} miniconda.sh" > anaconda.sha256 && \
+#    sha256sum --strict -c anaconda.sha256 && \
+#    bash miniconda.sh -b -p /opt/conda && \
+#    export PATH=/opt/conda/bin:$PATH && \
+#    conda config --set always_yes yes --set changeps1 no && \
+#    conda info -a && \
+#    conda install mamba -c conda-forge && \
+#    mamba env update -f /env_python_3_with_R.yml --prune && \
+#    # Cleanup
+#    rm -v miniconda.sh anaconda.sha256  && \
+#    # Cleanup based on https://github.com/ContinuumIO/docker-images/commit/cac3352bf21a26fa0b97925b578fb24a0fe8c383
+#    find /opt/conda/ -follow -type f -name '*.a' -delete && \
+#    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
+#    mamba clean -ay \
 COPY env_python_3_with_R.yml /env_python_3_with_R.yml
-COPY Miniconda3-${miniconda_version}-Linux-x86_64.sh /miniconda.sh
+# To improve the build time, the Zeppelin team recommends a conda proxy
+# COPY condarc /etc/conda/condarc
+# Allow to modify conda packages. This allows malicious code to be injected into other interpreter sessions, therefore it is disabled by default
+# chmod -R ug+rwX /opt/conda
 RUN set -ex && \
-    #wget -nv https://repo.anaconda.com/miniconda/Miniconda3-${miniconda_version}-Linux-x86_64.sh -O miniconda.sh && \
-    echo "${miniconda_sha256} miniconda.sh" > anaconda.sha256 && \
-    sha256sum --strict -c anaconda.sha256 && \
-    bash miniconda.sh -b -p /opt/conda && \
-    export PATH=/opt/conda/bin:$PATH && \
-    conda config --set always_yes yes --set changeps1 no && \
-    conda info -a && \
-    conda install mamba -c conda-forge && \
-    mamba env update -f /env_python_3_with_R.yml --prune && \
-    # Cleanup
-    rm -v miniconda.sh anaconda.sha256  && \
-    # Cleanup based on https://github.com/ContinuumIO/docker-images/commit/cac3352bf21a26fa0b97925b578fb24a0fe8c383
-    find /opt/conda/ -follow -type f -name '*.a' -delete && \
-    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
-    mamba clean -ay
-    # Allow to modify conda packages. This allows malicious code to be injected into other interpreter sessions, therefore it is disabled by default
-    # chmod -R ug+rwX /opt/conda
+    micromamba create -y -p /opt/conda -f env_python_3_with_R.yml && \
+    micromamba clean -ay
+
+
 ENV PATH /opt/conda/envs/python_3_with_R/bin:/opt/conda/bin:$PATH
 
 USER 1000
